# render.yaml
services:
  - type: web
    name: portofolio-meja-ghani
    env: php
    plan: free
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      chmod -R 755 writable
    startCommand: php -S 0.0.0.0:$PORT -t public
    envVars:
      - key: CI_ENVIRONMENT
        value: production